# Generated by Django 4.1.2 on 2023-06-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postalcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
