# Generated by Django 4.1.2 on 2023-01-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('mrp_price', models.FloatField()),
                ('list_price', models.FloatField()),
                ('category', models.CharField(max_length=70)),
                ('discount', models.IntegerField()),
                ('description', models.TextField()),
                ('speciality', models.TextField()),
                ('image', models.ImageField(default='abc.jpg', upload_to='images/')),
            ],
            options={
                'db_table': 'pname',
            },
        ),
    ]
