# Generated by Django 4.1.2 on 2023-01-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='mrp_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
