# Generated by Django 4.1.2 on 2023-01-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_alter_productdetails_mrp_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='list_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
