# Generated by Django 4.1.2 on 2023-01-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0007_alter_productdetails_list_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='speciality',
            field=models.TextField(null=True),
        ),
    ]
