# Generated by Django 4.1.2 on 2023-06-02 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0011_addtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.cart'),
        ),
    ]
