# Generated by Django 4.1.2 on 2023-06-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0014_addart_cartuser_delete_addtocart_delete_cart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addart',
            new_name='AddCart',
        ),
    ]
