# Generated by Django 4.1.2 on 2023-06-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0015_rename_addart_addcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcart',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
