# Generated by Django 4.1.2 on 2023-06-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0022_paymentcart_addtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcart',
            name='totalAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcart',
            name='totalQuantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
