# Generated by Django 4.1.2 on 2023-06-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0023_alter_paymentcart_totalamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='image',
            field=models.ImageField(null=True, upload_to='cartImage/'),
        ),
    ]
