# Generated by Django 4.1.2 on 2023-06-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0026_alter_addtocart_id_alter_paymentcart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='carts',
            new_name='cart',
        ),
    ]
