# Generated by Django 4.1.2 on 2023-06-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0027_rename_carts_addtocart_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='users',
            new_name='user',
        ),
    ]
