# Generated by Django 4.1.2 on 2023-06-21 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0028_rename_users_addtocart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ProductApp.paymentcart'),
        ),
    ]
