# Generated by Django 4.1.2 on 2023-06-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0029_alter_addtocart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
