# Generated by Django 4.1.2 on 2023-06-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0030_alter_addtocart_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
