# Generated by Django 4.1.2 on 2023-06-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0031_alter_addtocart_mrp_alter_addtocart_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('totalQuantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.paymentcart')),
            ],
        ),
    ]
