# Generated by Django 4.1.2 on 2023-06-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0033_vieworder_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vieworder',
            name='user',
        ),
    ]
