# Generated by Django 4.1.2 on 2023-06-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0036_alter_vieworder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vieworder',
            name='user',
        ),
    ]
