# Generated by Django 4.1.2 on 2023-06-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0038_vieworder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(default='active', max_length=100)),
            ],
        ),
    ]
