# Generated by Django 4.1.2 on 2023-06-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0039_orserstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrserStatus',
        ),
    ]
