# Generated by Django 4.1.2 on 2023-07-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0040_delete_orserstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vieworder',
            name='user',
        ),
    ]
